# API
DEFAULT_BASE_URL = "https://api.overshoot.ai/v0.2"

# Clip mode defaults
DEFAULT_TARGET_FPS = 6
DEFAULT_CLIP_LENGTH_SECONDS = 0.5
DEFAULT_DELAY_SECONDS = 0.5

# Frame mode defaults
DEFAULT_INTERVAL_SECONDS = 0.5

# Keepalive
KEEPALIVE_MAX_RETRIES = 3
KEEPALIVE_RETRY_DELAY = 2.0

# WebSocket reconnection
WS_RECONNECT_BASE_SECONDS = 1.0
WS_RECONNECT_MAX_SECONDS = 10.0
WS_RECONNECT_MAX_ATTEMPTS = 5
